<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'a315ad632f3103615807f6b0773fb73d',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/app?serverVersion=5.7',
);
